version = 0.1
[default.deploy.parameters]
stack_name = "ide-stack"
resolve_s3 = true
s3_prefix = "ide-stack"
region = "us-east-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "SsmParameterValueawsserviceamiamazonlinuxlatestal2023amikernel61x8664C96584B6F00A464EAD1953AFF4B05118Parameter=\"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64\""
image_repositories = []
